version: '3.8'

services:
  web:
    container_name: php-app
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
    ports:
      - 80:80
  
  db:
    container_name: php-db
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: VEHICULE_CIRCULATION
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

  adminer:
    container_name: db-manager
    image: adminer:4.7
    ports:
      - 8080:8080